// ============================================================
//  ALPHABET & WRITING SYSTEMS DATA — ARUKAS 2
//  100% Comprehensive Reference for 11 World Languages
// ============================================================

import { LanguageCode } from '../types';

export interface AlphabetCharacter {
  char: string;
  name?: string;
  reading?: string; // Transcription / Pinyin / Romaji / IPA
  meaningOrExample?: string;
  category?: string;
}

export interface WritingSystemSection {
  title: string;
  description?: string;
  characters: AlphabetCharacter[];
}

export interface LanguageAlphabetGuide {
  lang: LanguageCode;
  title: string;
  systemType: string;
  description: string;
  sections: WritingSystemSection[];
}

export const ALPHABET_GUIDES: Record<LanguageCode, LanguageAlphabetGuide> = {
  // ──────────────────────────────────────────────────────────
  //  1. VIỆT NAM (vi)
  // ──────────────────────────────────────────────────────────
  vi: {
    lang: 'vi',
    title: 'Hệ Thống Chữ Quốc Ngữ (Tiếng Việt)',
    systemType: 'Bảng chữ cái Latinh mở rộng kèm 6 thanh điệu',
    description: 'Chữ Quốc ngữ gồm 29 chữ cái chính thức, 6 thanh điệu (kể cả không dấu), 11 phụ âm ghép và các nguyên âm đôi/ba.',
    sections: [
      {
        title: 'Bảng 29 Chữ Cái Chính Thức',
        description: 'Chữ hoa, chữ thường và tên gọi chuẩn theo Bộ Giáo Dục & Đào Tạo.',
        characters: [
          { char: 'A a', name: 'A', reading: '/aː/', meaningOrExample: 'An toàn, Áo ấm' },
          { char: 'Ă ă', name: 'Á', reading: '/a/', meaningOrExample: 'Ăn cơm, Mặt trăng' },
          { char: 'Â â', name: 'Ớ', reading: '/ɜ/', meaningOrExample: 'Ấm áp, Cây cối' },
          { char: 'B b', name: 'Bê', reading: '/ɓ/', meaningOrExample: 'Bạn bè, Bầu trời' },
          { char: 'C c', name: 'Xê', reading: '/k/', meaningOrExample: 'Con cá, Cười vui' },
          { char: 'D d', name: 'Dê', reading: '/z/ (B) /j/ (N)', meaningOrExample: 'Dịu dàng, Dòng sông' },
          { char: 'Đ đ', name: 'Đê', reading: '/ɗ/', meaningOrExample: 'Đường đi, Đất nước' },
          { char: 'E e', name: 'E', reading: '/ɛ/', meaningOrExample: 'Em bé, Mẹ hiền' },
          { char: 'Ê ê', name: 'Ê', reading: '/e/', meaningOrExample: 'Êm đềm, Bếp lửa' },
          { char: 'G g', name: 'Giê', reading: '/ɣ/', meaningOrExample: 'Gần gũi, Gió mát' },
          { char: 'H h', name: 'Hát', reading: '/h/', meaningOrExample: 'Hạnh phúc, Hoa nở' },
          { char: 'I i', name: 'I ngắn', reading: '/i/', meaningOrExample: 'Im lặng, Trí tuệ' },
          { char: 'K k', name: 'Ca', reading: '/k/', meaningOrExample: 'Kính yêu, Kim chỉ' },
          { char: 'L l', name: 'E-lờ', reading: '/l/', meaningOrExample: 'Lung linh, Lòng son' },
          { char: 'M m', name: 'Em-mờ', reading: '/m/', meaningOrExample: 'Mặt trời, Mùa xuân' },
          { char: 'N n', name: 'En-nờ', reading: '/n/', meaningOrExample: 'Nụ cười, Nắng mai' },
          { char: 'O o', name: 'O', reading: '/ɔ/', meaningOrExample: 'Ong bướm, Trong veo' },
          { char: 'Ô ô', name: 'Ô', reading: '/o/', meaningOrExample: 'Ô che mưa, Tổ quốc' },
          { char: 'Ơ ơ', name: 'Ơ', reading: '/əː/', meaningOrExample: 'Ơn nghĩa, Lá cờ' },
          { char: 'P p', name: 'Pê', reading: '/p/', meaningOrExample: 'Phố xá, Phép màu' },
          { char: 'Q q', name: 'Quy', reading: '/k/', meaningOrExample: 'Quê hương, Quả ngọt' },
          { char: 'R r', name: 'E-rờ', reading: '/z/ (B) /ʐ/ (N)', meaningOrExample: 'Rực rỡ, Rừng xanh' },
          { char: 'S s', name: 'Ét-xì', reading: '/s/ (B) /ʂ/ (N)', meaningOrExample: 'Sáng suốt, Sóng biển' },
          { char: 'T t', name: 'Tê', reading: '/t/', meaningOrExample: 'Tương lai, Tình yêu' },
          { char: 'U u', name: 'U', reading: '/u/', meaningOrExample: 'Uống nước, Củi khô' },
          { char: 'Ư ư', name: 'Ư', reading: '/ɨ/', meaningOrExample: 'Ước mơ, Cơn mưa' },
          { char: 'V v', name: 'Vê', reading: '/v/', meaningOrExample: 'Vui vẻ, Vườn hoa' },
          { char: 'X x', name: 'Ích-xì', reading: '/s/', meaningOrExample: 'Xinh đẹp, Mùa xuân' },
          { char: 'Y y', name: 'I dài', reading: '/i/', meaningOrExample: 'Yêu thương, Ý chí' },
        ],
      },
      {
        title: '6 Thanh Điệu Tiếng Việt',
        description: 'Thanh điệu thay đổi cao độ và đường nét âm vực, biến đổi hoàn toàn nghĩa từ.',
        characters: [
          { char: 'Không dấu', name: 'Thanh Ngang', reading: 'Bằng phẳng (Cao vừa 33)', meaningOrExample: 'ba (người cha)' },
          { char: 'Dấu Huyền ( ` )', name: 'Thanh Huyền', reading: 'Hạ thấp dần (21)', meaningOrExample: 'bà (người bà)' },
          { char: 'Dấu Sắc ( ´ )', name: 'Thanh Sắc', reading: 'Lên cao dốc (35)', meaningOrExample: 'bá (bác, bá tước)' },
          { char: 'Dấu Hỏi ( ˀ )', name: 'Thanh Hỏi', reading: 'Xuống rồi lên (312)', meaningOrExample: 'bả (mồi bả)' },
          { char: 'Dấu Ngã ( ~ )', name: 'Thanh Ngã', reading: 'Gãy ở giữa, lên cao (325)', meaningOrExample: 'bã (bã trà)' },
          { char: 'Dấu Nặng ( . )', name: 'Thanh Nặng', reading: 'Hạ thấp dứt khoát (21ˀ)', meaningOrExample: 'bạ (bừa bãi)' },
        ],
      },
      {
        title: '11 Phụ Âm Ghép Tiếng Việt',
        description: 'Tổ hợp 2 hoặc 3 chữ cái biểu diễn một âm tố phụ âm độc lập.',
        characters: [
          { char: 'CH', reading: '/c/', meaningOrExample: 'Chim chóc, Chân thật' },
          { char: 'GH', reading: '/ɣ/', meaningOrExample: 'Ghi nhớ, Ghế gỗ (đứng trước e, ê, i)' },
          { char: 'GI', reading: '/z/ (B) /j/ (N)', meaningOrExample: 'Gió mát, Gia đình' },
          { char: 'KH', reading: '/x/', meaningOrExample: 'Khát khao, Khéo léo' },
          { char: 'NH', reading: '/ɲ/', meaningOrExample: 'Nhẹ nhàng, Nhớ nhung' },
          { char: 'NG', reading: '/ŋ/', meaningOrExample: 'Ngọt ngào, Ngân nga' },
          { char: 'NGH', reading: '/ŋ/', meaningOrExample: 'Nghĩ suy, Nghề nghiệp (trước e, ê, i)' },
          { char: 'PH', reading: '/f/', meaningOrExample: 'Phương trời, Phiêu lưu' },
          { char: 'QU', reading: '/kʷ/', meaningOrExample: 'Quê hương, Quý báu' },
          { char: 'TH', reading: '/tʰ/', meaningOrExample: 'Thanh bình, Tha thứ' },
          { char: 'TR', reading: '/c/ (B) /ʈ/ (N)', meaningOrExample: 'Trong sáng, Tre xanh' },
        ],
      },
      {
        title: 'Các Nguyên Âm Đôi & Vần Phổ Biến',
        description: 'Sự chuyển dịch âm vực giữa hai nguyên âm trong một âm tiết.',
        characters: [
          { char: 'IA / IÊ / YÊ', reading: '/iə/', meaningOrExample: 'Tía má, Biển cả, Yêu thương' },
          { char: 'UA / UÔ', reading: '/uə/', meaningOrExample: 'Mùa xuân, Cuộc sống' },
          { char: 'ƯA / ƯƠ', reading: '/ɨə/', meaningOrExample: 'Cơn mưa, Nước non' },
          { char: 'AI / AY / ÂY', reading: 'vần -i', meaningOrExample: 'Ban mai, Ngày mai, Cây cối' },
          { char: 'AO / AU / ÂU', reading: 'vần -u', meaningOrExample: 'Ngôi sao, Màu sắc, Nắng sầu' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  2. NHẬT BẢN (ja)
  // ──────────────────────────────────────────────────────────
  ja: {
    lang: 'ja',
    title: 'Hệ Thống Chữ Viết Tiếng Nhật (Kana & Kanji)',
    systemType: 'Bộ ba chữ viết: Hiragana, Katakana và Kanji',
    description: 'Bao gồm trọn vẹn 46 ký tự Hiragana (chữ mềm), 46 ký tự Katakana (chữ cứng), 25 âm đục/bán đục và 36 âm ghép.',
    sections: [
      {
        title: 'Hiragana Cơ Bản (46 Chữ Căn Bản - 平仮名)',
        description: 'Dùng ghi từ thuần Nhật, trợ từ ngữ pháp và đuôi biến âm của động từ/tính từ.',
        characters: [
          { char: 'あ', reading: 'a', meaningOrExample: '朝 (asa - buổi sáng)' },
          { char: 'い', reading: 'i', meaningOrExample: '犬 (inu - con chó)' },
          { char: 'う', reading: 'u', meaningOrExample: '海 (umi - biển)' },
          { char: 'え', reading: 'e', meaningOrExample: '駅 (eki - nhà ga)' },
          { char: 'お', reading: 'o', meaningOrExample: 'お茶 (ocha - tách trà)' },
          { char: 'か', reading: 'ka', meaningOrExample: '傘 (kasa - chiếc ô)' },
          { char: 'き', reading: 'ki', meaningOrExample: '木 (ki - cái cây)' },
          { char: 'く', reading: 'ku', meaningOrExample: '車 (kuruma - xe hơi)' },
          { char: 'け', reading: 'ke', meaningOrExample: '煙 (kemuri - khói)' },
          { char: 'こ', reading: 'ko', meaningOrExample: '声 (koe - tiếng nói)' },
          { char: 'さ', reading: 'sa', meaningOrExample: '桜 (sakura - hoa anh đào)' },
          { char: 'し', reading: 'shi', meaningOrExample: '白 (shiro - màu trắng)' },
          { char: 'す', reading: 'su', meaningOrExample: '寿司 (sushi)' },
          { char: 'せ', reading: 'se', meaningOrExample: '世界 (sekai - thế giới)' },
          { char: 'そ', reading: 'so', meaningOrExample: '空 (sora - bầu trời)' },
          { char: 'た', reading: 'ta', meaningOrExample: '太陽 (taiyou - mặt trời)' },
          { char: 'ち', reading: 'chi', meaningOrExample: '父 (chichi - người cha)' },
          { char: 'つ', reading: 'tsu', meaningOrExample: '月 (tsuki - mặt trăng)' },
          { char: 'て', reading: 'te', meaningOrExample: '手 (te - bàn tay)' },
          { char: 'と', reading: 'to', meaningOrExample: '友達 (tomodachi - bạn bè)' },
          { char: 'な', reading: 'na', meaningOrExample: '夏 (natsu - mùa hè)' },
          { char: 'に', reading: 'ni', meaningOrExample: '虹 (niji - cầu vồng)' },
          { char: 'ぬ', reading: 'nu', meaningOrExample: '布 (nuno - tấm vải)' },
          { char: 'ね', reading: 'ne', meaningOrExample: '猫 (neko - con mèo)' },
          { char: 'の', reading: 'no', meaningOrExample: '野原 (nohara - cánh đồng)' },
          { char: 'は', reading: 'ha', meaningOrExample: '花 (hana - bông hoa)' },
          { char: 'ひ', reading: 'hi', meaningOrExample: '光 (hikari - ánh sáng)' },
          { char: 'ふ', reading: 'fu', meaningOrExample: '冬 (fuyu - mùa đông)' },
          { char: 'へ', reading: 'he', meaningOrExample: '平和 (heiwa - hòa bình)' },
          { char: 'ほ', reading: 'ho', meaningOrExample: '星 (hoshi - ngôi sao)' },
          { char: 'ま', reading: 'ma', meaningOrExample: '街 (machi - thành phố)' },
          { char: 'み', reading: 'mi', meaningOrExample: '道 (michi - con đường)' },
          { char: 'む', reading: 'mu', meaningOrExample: '村 (mura - ngôi làng)' },
          { char: 'め', reading: 'me', meaningOrExample: '目 (me - đôi mắt)' },
          { char: 'も', reading: 'mo', meaningOrExample: '森 (mori - khu rừng)' },
          { char: 'や', reading: 'ya', meaningOrExample: '山 (yama - ngọn núi)' },
          { char: 'ゆ', reading: 'yu', meaningOrExample: '雪 (yuki - tuyết trắng)' },
          { char: 'よ', reading: 'yo', meaningOrExample: '夜 (yoru - đêm tối)' },
          { char: 'ら', reading: 'ra', meaningOrExample: '雷 (kaminari - sấm sét)' },
          { char: 'り', reading: 'ri', meaningOrExample: '林檎 (ringo - quả táo)' },
          { char: 'る', reading: 'ru', meaningOrExample: '留守 (rusu - vắng nhà)' },
          { char: 'れ', reading: 're', meaningOrExample: '歴史 (rekishi - lịch sử)' },
          { char: 'ろ', reading: 'ro', meaningOrExample: '蝋燭 (rousoku - cây nến)' },
          { char: 'わ', reading: 'wa', meaningOrExample: '私 (watashi - tôi)' },
          { char: 'を', reading: 'wo (o)', meaningOrExample: 'Trợ từ tân ngữ' },
          { char: 'ん', reading: 'n', meaningOrExample: '本 (hon - cuốn sách)' },
        ],
      },
      {
        title: 'Katakana Cơ Bản (Trọn Bộ 46 Chữ - 片仮名)',
        description: 'Dùng cho từ vay mượn tiếng nước ngoài, tên người nước ngoài và từ tượng thanh.',
        characters: [
          { char: 'ア', reading: 'a', meaningOrExample: 'アイス (kem)' },
          { char: 'イ', reading: 'i', meaningOrExample: 'インターネット (internet)' },
          { char: 'ウ', reading: 'u', meaningOrExample: 'ウイスキー (whisky)' },
          { char: 'エ', reading: 'e', meaningOrExample: 'エネルギー (năng lượng)' },
          { char: 'オ', reading: 'o', meaningOrExample: 'オレンジ (cam)' },
          { char: 'カ', reading: 'ka', meaningOrExample: 'カメラ (máy ảnh)' },
          { char: 'キ', reading: 'ki', meaningOrExample: 'キーボード (bàn phím)' },
          { char: 'ク', reading: 'ku', meaningOrExample: 'クラス (lớp học)' },
          { char: 'ケ', reading: 'ke', meaningOrExample: 'ケーキ (bánh kem)' },
          { char: 'コ', reading: 'ko', meaningOrExample: 'コーヒー (cà phê)' },
          { char: 'サ', reading: 'sa', meaningOrExample: 'サラダ (salad)' },
          { char: 'シ', reading: 'shi', meaningOrExample: 'シャツ (áo sơ mi)' },
          { char: 'ス', reading: 'su', meaningOrExample: 'スポーツ (thể thao)' },
          { char: 'セ', reading: 'se', meaningOrExample: 'センター (trung tâm)' },
          { char: 'ソ', reading: 'so', meaningOrExample: 'ソファー (ghế sofa)' },
          { char: 'タ', reading: 'ta', meaningOrExample: 'タクシー (taxi)' },
          { char: 'チ', reading: 'chi', meaningOrExample: 'チケット (vé)' },
          { char: 'ツ', reading: 'tsu', meaningOrExample: 'ツアー (tour du lịch)' },
          { char: 'テ', reading: 'te', meaningOrExample: 'テレビ (tivi)' },
          { char: 'ト', reading: 'to', meaningOrExample: 'トマト (cà chua)' },
          { char: 'ナ', reading: 'na', meaningOrExample: 'ナイフ (con dao)' },
          { char: 'ニ', reading: 'ni', meaningOrExample: 'ニュース (tin tức)' },
          { char: 'ヌ', reading: 'nu', meaningOrExample: 'ヌードル (mì)' },
          { char: 'ネ', reading: 'ne', meaningOrExample: 'ネクタイ (cà vạt)' },
          { char: 'ノ', reading: 'no', meaningOrExample: 'ノート (vở ghi)' },
          { char: 'ハ', reading: 'ha', meaningOrExample: 'ハンバーガー (burger)' },
          { char: 'ヒ', reading: 'hi', meaningOrExample: 'ヒーター (máy sưởi)' },
          { char: 'フ', reading: 'fu', meaningOrExample: 'フォーク (cái nĩa)' },
          { char: 'ヘ', reading: 'he', meaningOrExample: 'ヘリコプター (trực thăng)' },
          { char: 'ホ', reading: 'ho', meaningOrExample: 'ホテル (khách sạn)' },
          { char: 'マ', reading: 'ma', meaningOrExample: 'マスク (khẩu trang)' },
          { char: 'ミ', reading: 'mi', meaningOrExample: 'ミルク (sữa)' },
          { char: 'ム', reading: 'mu', meaningOrExample: 'ムービー (phim)' },
          { char: 'メ', reading: 'me', meaningOrExample: 'メニュー (thực đơn)' },
          { char: 'モ', reading: 'mo', meaningOrExample: 'モデル (người mẫu)' },
          { char: 'ヤ', reading: 'ya', meaningOrExample: 'ヤング (trẻ trung)' },
          { char: 'ユ', reading: 'yu', meaningOrExample: 'ユニフォーム (đồng phục)' },
          { char: 'ヨ', reading: 'yo', meaningOrExample: 'ヨーグルト (sữa chua)' },
          { char: 'ラ', reading: 'ra', meaningOrExample: 'ラジオ (đài radio)' },
          { char: 'リ', reading: 'ri', meaningOrExample: 'リモコン (điều khiển)' },
          { char: 'ル', reading: 'ru', meaningOrExample: 'ルール (luật lệ)' },
          { char: 'レ', reading: 're', meaningOrExample: 'レストラン (nhà hàng)' },
          { char: 'ロ', reading: 'ro', meaningOrExample: 'ロボット (người máy)' },
          { char: 'ワ', reading: 'wa', meaningOrExample: 'ワイン (rượu vang)' },
          { char: 'ヲ', reading: 'wo', meaningOrExample: 'ヲ (hiếm dùng)' },
          { char: 'ン', reading: 'n', meaningOrExample: 'パン (bánh mì)' },
        ],
      },
      {
        title: 'Âm Đục & Bán Đục (Dakuten & Handakuten - 濁音・半濁音)',
        description: 'Thêm dấu ゛(tenten) hoặc ゜(maru) vào các hàng か, さ, た, は.',
        characters: [
          { char: 'が ぎ ぐ げ ご', reading: 'ga gi gu ge go', meaningOrExample: '学校 (gakkou - trường học)' },
          { char: 'ざ じ ず ぜ ぞ', reading: 'za ji zu ze zo', meaningOrExample: '雑誌 (zasshi - tạp chí)' },
          { char: 'だ ぢ づ で ど', reading: 'da ji zu de do', meaningOrExample: '電話 (denwa - điện thoại)' },
          { char: 'ば び ぶ べ ぼ', reading: 'ba bi bu be bo', meaningOrExample: '文学 (bungaku - văn học)' },
          { char: 'ぱ ぴ ぷ ぺ ぽ', reading: 'pa pi pu pe po', meaningOrExample: '心配 (shinpai - lo lắng)' },
        ],
      },
      {
        title: 'Âm Ghép (Yōon - 拗音)',
        description: 'Kết hợp âm hàng い với や, ゆ, よ viết nhỏ.',
        characters: [
          { char: 'きゃ きゅ きょ', reading: 'kya kyu kyo', meaningOrExample: '今日 (kyou - hôm nay)' },
          { char: 'しゃ しゅ しょ', reading: 'sha shu sho', meaningOrExample: '写真 (shashin - ảnh)' },
          { char: 'ちゃ ちゅ ちょ', reading: 'cha chu cho', meaningOrExample: 'お茶 (ocha - trà)' },
          { char: 'にゃ にゅ にょ', reading: 'nya nyu nyo', meaningOrExample: '牛乳 (gyuunyuu - sữa)' },
          { char: 'ひゃ ひゅ ひょ', reading: 'hya hyu hyo', meaningOrExample: '百 (hyaku - một trăm)' },
          { char: 'みゃ みゅ みょ', reading: 'mya myu myo', meaningOrExample: '苗字 (myouji - họ)' },
          { char: 'りゃ りゅ りょ', reading: 'rya ryu ryo', meaningOrExample: '旅行 (ryokou - du lịch)' },
          { char: 'ぎゃ ぎゅ ぎょ', reading: 'gya gyu gyo', meaningOrExample: '金魚 (kingyo - cá vàng)' },
          { char: 'じゃ じゅ じょ', reading: 'ja ju jo', meaningOrExample: '邪魔 (jama - cản trở)' },
          { char: 'びゃ びゅ びょ', reading: 'bya byu byo', meaningOrExample: '病院 (byouin - bệnh viện)' },
          { char: 'ぴゃ ぴゅ ぴょ', reading: 'pya pyu pyo', meaningOrExample: '発表 (happyou - phát biểu)' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  3. HÀN QUỐC (ko)
  // ──────────────────────────────────────────────────────────
  ko: {
    lang: 'ko',
    title: 'Hệ Thống Chữ Viết Hangeul (Tiếng Hàn)',
    systemType: 'Bảng chữ cái khoa học tượng hình âm vị (한글)',
    description: 'Do vua Sejong sáng tạo năm 1443. Gồm 19 phụ âm, 21 nguyên âm và hệ thống âm cuối Batchim phong phú.',
    sections: [
      {
        title: '14 Phụ Âm Cơ Bản (자음)',
        description: 'Mô phỏng hình dáng cơ quan phát âm trong khoang miệng.',
        characters: [
          { char: 'ㄱ', name: 'Giyeok', reading: 'g / k', meaningOrExample: '가방 (gabang - chiếc cặp)' },
          { char: 'ㄴ', name: 'Nieun', reading: 'n', meaningOrExample: '나무 (namu - cái cây)' },
          { char: 'ㄷ', name: 'Digeut', reading: 'd / t', meaningOrExample: '다리 (dari - cây cầu)' },
          { char: 'ㄹ', name: 'Rieul', reading: 'r / l', meaningOrExample: '라면 (ramyeon - mì gói)' },
          { char: 'ㅁ', name: 'Mieum', reading: 'm', meaningOrExample: '마음 (ma-eum - tấm lòng)' },
          { char: 'ㅂ', name: 'Bieup', reading: 'b / p', meaningOrExample: '바다 (bada - biển cả)' },
          { char: 'ㅅ', name: 'Siot', reading: 's', meaningOrExample: '사랑 (sarang - tình yêu)' },
          { char: 'ㅇ', name: 'Ieung', reading: 'câm / ng ở cuối', meaningOrExample: '아이 (a-i - đứa trẻ), 강 (gang - sông)' },
          { char: 'ㅈ', name: 'Jieut', reading: 'j / ch', meaningOrExample: '자유 (jayu - tự do)' },
          { char: 'ㅊ', name: 'Chieut', reading: 'ch (bật hơi)', meaningOrExample: '친구 (chingu - bạn bè)' },
          { char: 'ㅋ', name: 'Kieuk', reading: 'k (bật hơi)', meaningOrExample: '커피 (keopi - cà phê)' },
          { char: 'ㅌ', name: 'Tieut', reading: 't (bật hơi)', meaningOrExample: '태양 (taeyang - mặt trời)' },
          { char: 'ㅍ', name: 'Pieup', reading: 'p (bật hơi)', meaningOrExample: '포도 (podo - chùm nho)' },
          { char: 'ㅎ', name: 'Hieut', reading: 'h', meaningOrExample: '하늘 (haneul - bầu trời)' },
        ],
      },
      {
        title: '5 Phụ Âm Căng / Kép (쌍자음)',
        description: 'Phát âm gồng chặt dây thanh quản, không thoát khí.',
        characters: [
          { char: 'ㄲ', name: 'Ssang-giyeok', reading: 'kk', meaningOrExample: '꽃 (kkot - bông hoa)' },
          { char: 'ㄸ', name: 'Ssang-digeut', reading: 'tt', meaningOrExample: '떡 (tteok - bánh gạo)' },
          { char: 'ㅃ', name: 'Ssang-bieup', reading: 'pp', meaningOrExample: '빵 (ppang - bánh mì)' },
          { char: 'ㅆ', name: 'Ssang-siot', reading: 'ss', meaningOrExample: '쌀 (ssal - hạt gạo)' },
          { char: 'ㅉ', name: 'Ssang-jieut', reading: 'jj', meaningOrExample: '짜장면 (mì tương đen)' },
        ],
      },
      {
        title: '10 Nguyên Âm Cơ Bản (단모음)',
        description: 'Triết lý Thiên (•), Địa (ㅡ), Nhân (ㅣ).',
        characters: [
          { char: 'ㅏ', name: 'A', reading: 'a', meaningOrExample: '아버지 (cha)' },
          { char: 'ㅑ', name: 'Ya', reading: 'ya', meaningOrExample: '야구 (bóng chày)' },
          { char: 'ㅓ', name: 'Eo', reading: 'ơ / o', meaningOrExample: '어머니 (mẹ)' },
          { char: 'ㅕ', name: 'Yeo', reading: 'yơ / yo', meaningOrExample: '여름 (mùa hè)' },
          { char: 'ㅗ', name: 'O', reading: 'ô', meaningOrExample: '오빠 (anh trai)' },
          { char: 'ㅛ', name: 'Yo', reading: 'yô', meaningOrExample: '요리 (nấu ăn)' },
          { char: 'ㅜ', name: 'U', reading: 'u', meaningOrExample: '우유 (sữa tươi)' },
          { char: 'ㅠ', name: 'Yu', reading: 'yu', meaningOrExample: '유리 (thủy tinh)' },
          { char: 'ㅡ', name: 'Eu', reading: 'ư', meaningOrExample: '음악 (âm nhạc)' },
          { char: 'ㅣ', name: 'I', reading: 'i', meaningOrExample: '이름 (tên)' },
        ],
      },
      {
        title: '11 Nguyên Âm Ghép (복모음)',
        description: 'Tổ hợp từ các nét nguyên âm cơ bản.',
        characters: [
          { char: 'ㅐ', name: 'Ae', reading: 'e / ae', meaningOrExample: '배 (bae - quả lê, chiếc thuyền)' },
          { char: 'ㅒ', name: 'Yae', reading: 'ye', meaningOrExample: '얘기 (yaegi - câu chuyện)' },
          { char: 'ㅔ', name: 'E', reading: 'ê', meaningOrExample: '세계 (segye - thế giới)' },
          { char: 'ㅖ', name: 'Ye', reading: 'yê', meaningOrExample: '예술 (yesul - nghệ thuật)' },
          { char: 'ㅘ', name: 'Wa', reading: 'oa', meaningOrExample: '화가 (hwaga - họa sĩ)' },
          { char: 'ㅙ', name: 'Wae', reading: 'oe', meaningOrExample: '왜 (wae - tại sao)' },
          { char: 'ㅚ', name: 'Oe', reading: 'uê', meaningOrExample: '외국 (oeguk - nước ngoài)' },
          { char: 'ㅝ', name: 'Wo', reading: 'uơ', meaningOrExample: '월요일 (thứ Hai)' },
          { char: 'ㅞ', name: 'We', reading: 'uê', meaningOrExample: '웨딩 (wedding - đám cưới)' },
          { char: 'ㅟ', name: 'Wi', reading: 'uy', meaningOrExample: '위 (wi - ở trên, dạ dày)' },
          { char: 'ㅢ', name: 'Ui', reading: 'ưi / ê', meaningOrExample: '의사 (uisa - bác sĩ)' },
        ],
      },
      {
        title: '7 Âm Cuối Chuẩn (Batchim - 받침)',
        description: 'Tất cả các phụ âm khi đứng ở vị trí âm cuối đều quy về 7 âm phát chuẩn.',
        characters: [
          { char: 'ㄱ, ㅋ, ㄲ, ㄳ, ㄺ', name: 'Đọc là [k]', reading: 'ngậm môi cản gió', meaningOrExample: '책 (sách), 밖 (ngoài), 닭 (con gà)' },
          { char: 'ㄴ, ㄵ, ㄶ', name: 'Đọc là [n]', reading: 'đầu lưỡi chạm lợi', meaningOrExample: '눈 (mắt, tuyết), 앉다 (ngồi)' },
          { char: 'ㄷ, ㅅ, ㅈ, ㅊ, ㅌ, ㅎ, ㅆ', name: 'Đọc là [t]', reading: 'chặn hơi răng', meaningOrExample: '옷 (áo), 꽃 (hoa), 끝 (kết thúc)' },
          { char: 'ㄹ, ㄼ, ㄽ, ㄾ, ㅀ', name: 'Đọc là [l]', reading: 'uốn lưỡi chạm hàm trên', meaningOrExample: '달 (mặt trăng), 말 (ngựa, lời nói)' },
          { char: 'ㅁ, ㄻ', name: 'Đọc là [m]', reading: 'khép chặt hai môi', meaningOrExample: '밤 (đêm tối), 삶 (cuộc đời)' },
          { char: 'ㅂ, ㅍ, ㄿ, ㅄ', name: 'Đọc là [p]', reading: 'ngậm hai môi', meaningOrExample: '밥 (cơm), 잎 (chiếc lá), 값 (giá cả)' },
          { char: 'ㅇ', name: 'Đọc là [ng]', reading: 'âm mũi vòm họng', meaningOrExample: '사랑 (tình yêu), 강 (dòng sông)' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  4. TRUNG QUỐC (zh)
  // ──────────────────────────────────────────────────────────
  zh: {
    lang: 'zh',
    title: 'Hệ Thống Pinyin & Chữ Hán (Tiếng Trung)',
    systemType: 'Chữ Hán biểu ý kết hợp hệ thống phiên âm Pinyin',
    description: 'Bao gồm 21 thanh mẫu (phụ âm đầu), 36 vận mẫu (vần/nguyên âm), 4 thanh điệu chính và các bộ thủ Hán tự.',
    sections: [
      {
        title: '4 Thanh Điệu Pinyin & Thanh Nhẹ',
        description: 'Thanh điệu thay đổi sẽ đổi hoàn toàn nghĩa của âm tiết.',
        characters: [
          { char: 'ā (Thanh 1)', name: 'Âm bình', reading: 'Cao, phẳng đều (55)', meaningOrExample: 'mā (妈 - mẹ)' },
          { char: 'á (Thanh 2)', name: 'Dương bình', reading: 'Từ trung lên cao (35)', meaningOrExample: 'má (麻 - cây gai)' },
          { char: 'ǎ (Thanh 3)', name: 'Thượng thanh', reading: 'Xuống thấp rồi lên (214)', meaningOrExample: 'mǎ (马 - con ngựa)' },
          { char: 'à (Thanh 4)', name: 'Khứ thanh', reading: 'Rơi dứt khoát từ cao xuống thấp (51)', meaningOrExample: 'mà (骂 - mắng mỏ)' },
          { char: 'ma (Thanh nhẹ)', name: 'Khinh thanh', reading: 'Phát âm ngắn, nhẹ', meaningOrExample: 'ma (吗 - trợ từ nghi vấn)' },
        ],
      },
      {
        title: '21 Thanh Mẫu (Phụ Âm Đầu - 声母)',
        description: 'Tất cả phụ âm mở đầu âm tiết trong tiếng Trung phổ thông.',
        characters: [
          { char: 'b', reading: '[p] (pô)', meaningOrExample: '爸爸 (bàba - cha)' },
          { char: 'p', reading: '[pʰ] (pô bật hơi)', meaningOrExample: '朋友 (péngyou - bạn bè)' },
          { char: 'm', reading: '[m] (mô)', meaningOrExample: '妈妈 (māma - mẹ)' },
          { char: 'f', reading: '[f] (phô)', meaningOrExample: '飞机 (fēijī - máy bay)' },
          { char: 'd', reading: '[t] (tưa)', meaningOrExample: '大地 (dàdì - đại địa)' },
          { char: 't', reading: '[tʰ] (thưa bật hơi)', meaningOrExample: '太阳 (tàiyáng - mặt trời)' },
          { char: 'n', reading: '[n] (nưa)', meaningOrExample: '南方 (nánfāng - phương nam)' },
          { char: 'l', reading: '[l] (lưa)', meaningOrExample: '老师 (lǎoshī - giáo viên)' },
          { char: 'g', reading: '[k] (cưa)', meaningOrExample: '国家 (guójiā - quốc gia)' },
          { char: 'k', reading: '[kʰ] (khưa bật hơi)', meaningOrExample: '开心 (kāixīn - vui vẻ)' },
          { char: 'h', reading: '[x] (hưa nhẹ)', meaningOrExample: '和平 (hépíng - hòa bình)' },
          { char: 'j', reading: '[tɕ] (chi)', meaningOrExample: '今天 (jīntiān - hôm nay)' },
          { char: 'q', reading: '[tɕʰ] (chi bật hơi)', meaningOrExample: '青春 (qīngchūn - thanh xuân)' },
          { char: 'x', reading: '[ɕ] (xi)', meaningOrExample: '希望 (xīwàng - hy vọng)' },
          { char: 'zh', reading: '[ʈʂ] (tr- uốn lưỡi)', meaningOrExample: '中国 (zhōngguó - Trung Quốc)' },
          { char: 'ch', reading: '[ʈʂʰ] (tr- bật hơi uốn lưỡi)', meaningOrExample: '春风 (chūnfēng - gió xuân)' },
          { char: 'sh', reading: '[ʂ] (s- uốn lưỡi)', meaningOrExample: '山水 (shānshuǐ - non nước)' },
          { char: 'r', reading: '[ʐ] (r- uốn lưỡi)', meaningOrExample: '热情 (rèqíng - nhiệt tình)' },
          { char: 'z', reading: '[ts] (ch- thẳng lưỡi)', meaningOrExample: '自己 (zìjǐ - tự mình)' },
          { char: 'c', reading: '[tsʰ] (ch- bật hơi thẳng lưỡi)', meaningOrExample: '彩虹 (cǎihóng - cầu vồng)' },
          { char: 's', reading: '[s] (x- thẳng lưỡi)', meaningOrExample: '森林 (sēnlín - rừng rậm)' },
        ],
      },
      {
        title: '36 Vận Mẫu (Vần / Nguyên Âm - 韵母)',
        description: 'Gồm vận mẫu đơn, kép, mũi trước (-n) và mũi sau (-ng).',
        characters: [
          { char: 'a, o, e, i, u, ü', reading: 'Vận mẫu đơn', meaningOrExample: '大 (dà), 多 (duō), 绿 (lǜ)' },
          { char: 'ai, ei, ui, ao, ou, iu', reading: 'Vận mẫu kép 1', meaningOrExample: '爱 (ài), 飞 (fēi), 水 (shuǐ)' },
          { char: 'ie, üe, er', reading: 'Vận mẫu kép 2', meaningOrExample: '月 (yuè), 耳 (ěr - tai)' },
          { char: 'an, en, in, un, ün', reading: 'Vận mẫu mũi trước (-n)', meaningOrExample: '心 (xīn), 云 (yún - mây)' },
          { char: 'ang, eng, ing, ong', reading: 'Vận mẫu mũi sau (-ng)', meaningOrExample: '风 (fēng), 红 (hóng - đỏ)' },
          { char: 'ia, iao, ian, iang, iong', reading: 'Vận mẫu bắt đầu bằng i', meaningOrExample: '江 (jiāng), 龙 (lóng - rồng)' },
          { char: 'ua, uo, uai, uan, uang', reading: 'Vận mẫu bắt đầu bằng u', meaningOrExample: '光 (guāng), 花 (huā - hoa)' },
        ],
      },
      {
        title: 'Các Bộ Thủ Chữ Hán Cốt Lõi',
        description: 'Chìa khóa hiểu ý nghĩa của hàng vạn chữ Hán.',
        characters: [
          { char: '亻 (Nhân)', reading: 'rén', meaningOrExample: 'Liên quan đến con người: 你 (bạn), 他 (anh ấy)' },
          { char: '氵 (Thủy)', reading: 'shuǐ', meaningOrExample: 'Liên quan đến nước: 海 (biển), 江 (sông), 河 (hà)' },
          { char: '木 (Mộc)', reading: 'mù', meaningOrExample: 'Liên quan cây cối: 树 (cây), 林 (rừng)' },
          { char: '火 / 灬 (Hỏa)', reading: 'huǒ', meaningOrExample: 'Liên quan đến lửa, nhiệt: 热 (nóng), 烤 (nướng)' },
          { char: '口 (Khẩu)', reading: 'kǒu', meaningOrExample: 'Liên quan miệng, lời nói: 吃 (ăn), 叫 (kêu)' },
          { char: '心 / 忄 (Tâm)', reading: 'xīn', meaningOrExample: 'Liên quan cảm xúc, ý nghĩ: 忙 (bận), 想 (nghĩ)' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  5. NGA (ru)
  // ──────────────────────────────────────────────────────────
  ru: {
    lang: 'ru',
    title: 'Bảng Chữ Cái Kirin (Tiếng Nga - Русский алфавит)',
    systemType: 'Bảng chữ cái Cyrillic gồm 33 chữ cái',
    description: '33 chữ cái gồm 10 nguyên âm (cặp cứng/mềm), 21 phụ âm và 2 dấu biểu âm phân cách.',
    sections: [
      {
        title: '33 Ký Tự Cyrillic Chuẩn',
        description: 'Chữ in hoa, in thường, phiên âm ngữ âm và từ vựng minh họa.',
        characters: [
          { char: 'А а', reading: '[a]', meaningOrExample: 'Август (tháng Tám)' },
          { char: 'Б б', reading: '[b]', meaningOrExample: 'Брат (người anh/em)' },
          { char: 'В в', reading: '[v]', meaningOrExample: 'Весна (mùa xuân)' },
          { char: 'Г г', reading: '[g]', meaningOrExample: 'Город (thành phố)' },
          { char: 'Д д', reading: '[d]', meaningOrExample: 'Друг (người bạn)' },
          { char: 'Е е', reading: '[je] / [e]', meaningOrExample: 'Европа (Châu Âu)' },
          { char: 'Ё ё', reading: '[jo]', meaningOrExample: 'Ёлка (cây thông Noel)' },
          { char: 'Ж ж', reading: '[ʐ] (zh cứng)', meaningOrExample: 'Жизнь (cuộc sống)' },
          { char: 'З з', reading: '[z]', meaningOrExample: 'Звезда (ngôi sao)' },
          { char: 'И и', reading: '[i]', meaningOrExample: 'История (lịch sử)' },
          { char: 'Й й', reading: '[j] (i ngắn)', meaningOrExample: 'Музей (bảo tàng)' },
          { char: 'К к', reading: '[k]', meaningOrExample: 'Книга (cuốn sách)' },
          { char: 'Л л', reading: '[l]', meaningOrExample: 'Любовь (tình yêu)' },
          { char: 'М м', reading: '[m]', meaningOrExample: 'Мир (thế giới, hòa bình)' },
          { char: 'Н н', reading: '[n]', meaningOrExample: 'Небо (bầu trời)' },
          { char: 'О о', reading: '[o] khi nhấn / [a] khi không nhấn', meaningOrExample: 'Окно (cửa sổ)' },
          { char: 'П п', reading: '[p]', meaningOrExample: 'Правда (sự thật)' },
          { char: 'Р р', reading: '[r] (rung lưỡi mạnh)', meaningOrExample: 'Россия (nước Nga)' },
          { char: 'С с', reading: '[s]', meaningOrExample: 'Солнце (mặt trời)' },
          { char: 'Т т', reading: '[t]', meaningOrExample: 'Театр (nhà hát)' },
          { char: 'У у', reading: '[u]', meaningOrExample: 'Улыбка (nụ cười)' },
          { char: 'Ф ф', reading: '[f]', meaningOrExample: 'Фотография (bức ảnh)' },
          { char: 'Х х', reading: '[x] (kh)', meaningOrExample: 'Хлеб (bánh mì)' },
          { char: 'Ц ц', reading: '[ts]', meaningOrExample: 'Цветок (bông hoa)' },
          { char: 'Ч ч', reading: '[tɕ] (ch mềm)', meaningOrExample: 'Чай (tách trà)' },
          { char: 'Ш ш', reading: '[ʂ] (s cứng)', meaningOrExample: 'Школа (trường học)' },
          { char: 'Щ щ', reading: '[ɕː] (shch mềm kéo dài)', meaningOrExample: 'Щедрость (hào phóng)' },
          { char: 'Ъ ъ', reading: 'Dấu cứng (Tverdy znak)', meaningOrExample: 'Объект (đối tượng)' },
          { char: 'Ы ы', reading: '[ɨ] (ư/i trầm sâu)', meaningOrExample: 'Музыка (âm nhạc)' },
          { char: 'Ь ь', reading: 'Dấu mềm (Myagkiy znak)', meaningOrExample: 'День (ngày, ban ngày)' },
          { char: 'Э э', reading: '[ɛ]', meaningOrExample: 'Эпоха (thời đại)' },
          { char: 'Ю ю', reading: '[ju]', meaningOrExample: 'Юность (tuổi trẻ)' },
          { char: 'Я я', reading: '[ja]', meaningOrExample: 'Яблоко (quả táo)' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  6. ANH (en)
  // ──────────────────────────────────────────────────────────
  en: {
    lang: 'en',
    title: 'Bảng Chữ Cái & Ngữ Âm IPA (Tiếng Anh)',
    systemType: '26 chữ cái Latinh kết hợp hệ thống 44 âm vị IPA chuẩn quốc tế',
    description: 'Gồm 26 chữ cái viết chuẩn và 44 âm vị IPA (12 nguyên âm đơn, 8 nguyên âm đôi, 24 phụ âm) theo Oxford.',
    sections: [
      {
        title: 'Bảng 26 Chữ Cái Latinh A-Z',
        description: 'Tên chữ cái và ví dụ phát âm chuẩn.',
        characters: [
          { char: 'A a', reading: '/eɪ/', meaningOrExample: 'Apple, Air' },
          { char: 'B b', reading: '/biː/', meaningOrExample: 'Brave, Blue' },
          { char: 'C c', reading: '/siː/', meaningOrExample: 'Calm, City' },
          { char: 'D d', reading: '/diː/', meaningOrExample: 'Dream, Dawn' },
          { char: 'E e', reading: '/iː/', meaningOrExample: 'Echo, Earth' },
          { char: 'F f', reading: '/ɛf/', meaningOrExample: 'Flame, Freedom' },
          { char: 'G g', reading: '/dʒiː/', meaningOrExample: 'Grace, Green' },
          { char: 'H h', reading: '/eɪtʃ/', meaningOrExample: 'Hope, Horizon' },
          { char: 'I i', reading: '/aɪ/', meaningOrExample: 'Island, Idea' },
          { char: 'J j', reading: '/dʒeɪ/', meaningOrExample: 'Joy, Journey' },
          { char: 'K k', reading: '/keɪ/', meaningOrExample: 'Kind, King' },
          { char: 'L l', reading: '/ɛl/', meaningOrExample: 'Light, Leaf' },
          { char: 'M m', reading: '/ɛm/', meaningOrExample: 'Moon, Music' },
          { char: 'N n', reading: '/ɛn/', meaningOrExample: 'Nature, Night' },
          { char: 'O o', reading: '/oʊ/', meaningOrExample: 'Ocean, Open' },
          { char: 'P p', reading: '/piː/', meaningOrExample: 'Peace, Poem' },
          { char: 'Q q', reading: '/kjuː/', meaningOrExample: 'Quiet, Quest' },
          { char: 'R r', reading: '/ɑːr/', meaningOrExample: 'Rain, River' },
          { char: 'S s', reading: '/ɛs/', meaningOrExample: 'Sun, Spirit' },
          { char: 'T t', reading: '/tiː/', meaningOrExample: 'Truth, Time' },
          { char: 'U u', reading: '/juː/', meaningOrExample: 'Universe, Unity' },
          { char: 'V v', reading: '/viː/', meaningOrExample: 'Voice, Valley' },
          { char: 'W w', reading: '/ˈdʌbəl.juː/', meaningOrExample: 'Water, Wind' },
          { char: 'X x', reading: '/ɛks/', meaningOrExample: 'Xylophone' },
          { char: 'Y y', reading: '/waɪ/', meaningOrExample: 'Youth, Year' },
          { char: 'Z z', reading: '/zɛd/ /ziː/', meaningOrExample: 'Zen, Zephyr' },
        ],
      },
      {
        title: '12 Nguyên Âm Đơn IPA (Monophthongs)',
        description: 'Bao gồm các cặp âm ngắn và âm dài có dấu hai chấm (:).',
        characters: [
          { char: '/iː/', reading: 'i dài', meaningOrExample: 'see /siː/, sheep' },
          { char: '/ɪ/', reading: 'i ngắn', meaningOrExample: 'sit /sɪt/, ship' },
          { char: '/ʊ/', reading: 'u ngắn', meaningOrExample: 'good /ɡʊd/, put' },
          { char: '/uː/', reading: 'u dài', meaningOrExample: 'shoot /ʃuːt/, blue' },
          { char: '/e/', reading: 'e ngắn', meaningOrExample: 'bed /bed/, men' },
          { char: '/ə/', reading: 'ơ nhẹ (schwa)', meaningOrExample: 'teacher /ˈtiːtʃər/, about' },
          { char: '/ɜː/', reading: 'ơ dài', meaningOrExample: 'bird /bɜːd/, learn' },
          { char: '/ɔː/', reading: 'o dài', meaningOrExample: 'door /dɔːr/, walk' },
          { char: '/æ/', reading: 'a bẹt (e-a)', meaningOrExample: 'cat /kæt/, apple' },
          { char: '/ʌ/', reading: 'á / ơ', meaningOrExample: 'cup /kʌp/, love' },
          { char: '/ɑː/', reading: 'a dài trầm', meaningOrExample: 'car /kɑːr/, heart' },
          { char: '/ɒ/', reading: 'o ngắn tròn môi', meaningOrExample: 'on /ɒn/, clock' },
        ],
      },
      {
        title: '8 Nguyên Âm Đôi IPA (Diphthongs)',
        description: 'Âm lướt chuyển tiếp giữa hai nguyên âm trong một hơi thở.',
        characters: [
          { char: '/ɪə/', reading: 'i-ơ', meaningOrExample: 'here /hɪər/, ear' },
          { char: '/eɪ/', reading: 'ê-i', meaningOrExample: 'day /deɪ/, wait' },
          { char: '/ʊə/', reading: 'u-ơ', meaningOrExample: 'tour /tʊər/, poor' },
          { char: '/ɔɪ/', reading: 'o-i', meaningOrExample: 'boy /bɔɪ/, coin' },
          { char: '/əʊ/', reading: 'ơ-u', meaningOrExample: 'show /ʃəʊ/, go' },
          { char: '/eə/', reading: 'e-ơ', meaningOrExample: 'hair /heər/, care' },
          { char: '/aɪ/', reading: 'a-i', meaningOrExample: 'my /maɪ/, time' },
          { char: '/aʊ/', reading: 'a-u', meaningOrExample: 'cow /kaʊ/, now' },
        ],
      },
      {
        title: '24 Phụ Âm IPA (Consonants)',
        description: 'Phân loại phụ âm vô thanh (Voiceless) và hữu thanh (Voiced).',
        characters: [
          { char: '/p/ & /b/', reading: 'p (bật hơi) vs b', meaningOrExample: 'pen /pen/ vs bed /bed/' },
          { char: '/t/ & /d/', reading: 't vs d', meaningOrExample: 'tea /tiː/ vs do /duː/' },
          { char: '/tʃ/ & /dʒ/', reading: 'ch vs dj', meaningOrExample: 'cheese /tʃiːz/ vs June /dʒuːn/' },
          { char: '/k/ & /g/', reading: 'k vs g', meaningOrExample: 'cat /kæt/ vs go /ɡəʊ/' },
          { char: '/f/ & /v/', reading: 'ph vs v', meaningOrExample: 'fly /flaɪ/ vs video /ˈvɪdiəʊ/' },
          { char: '/θ/ & /ð/', reading: 'th không thanh vs th hữu thanh', meaningOrExample: 'think /θɪŋk/ vs this /ðɪs/' },
          { char: '/s/ & /z/', reading: 'x vs d/z', meaningOrExample: 'see /siː/ vs zoo /zuː/' },
          { char: '/ʃ/ & /ʒ/', reading: 'sh nặng vs zh rung', meaningOrExample: 'shall /ʃæl/ vs vision /ˈvɪʒən/' },
          { char: '/m/, /n/, /ŋ/', reading: 'âm mũi: m, n, ng', meaningOrExample: 'man, now, sing /sɪŋ/' },
          { char: '/h/, /l/, /r/, /w/, /j/', reading: 'bán nguyên âm & phụ âm lướt', meaningOrExample: 'hat, red, wet, yes /jes/' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  7. TÂY BAN NHA (es)
  // ──────────────────────────────────────────────────────────
  es: {
    lang: 'es',
    title: 'Alfabeto Español (Tiếng Tây Ban Nha)',
    systemType: 'Bảng chữ cái Latinh 27 chữ cái chính thức',
    description: 'Gồm 27 chữ cái (kèm ký tự độc quyền Ñ), các nguyên âm có dấu trọng âm (Á, É, Í, Ó, Ú, Ü) và các chữ đôi Ch, Ll, Rr.',
    sections: [
      {
        title: '27 Chữ Cái Chính Thức',
        description: 'Bảng chữ cái quy chuẩn của Viện Hàn Lâm Hoàng Gia Tây Ban Nha (RAE).',
        characters: [
          { char: 'A a', reading: 'a', meaningOrExample: 'Amor (tình yêu)' },
          { char: 'B b', reading: 'be', meaningOrExample: 'Bueno (tốt lành)' },
          { char: 'C c', reading: 'ce', meaningOrExample: 'Cielo (bầu trời)' },
          { char: 'D d', reading: 'de', meaningOrExample: 'Día (ngày)' },
          { char: 'E e', reading: 'e', meaningOrExample: 'Estrella (ngôi sao)' },
          { char: 'F f', reading: 'efe', meaningOrExample: 'Fuego (ngọn lửa)' },
          { char: 'G g', reading: 'ge', meaningOrExample: 'Gato (con mèo)' },
          { char: 'H h', reading: 'hache (luôn câm)', meaningOrExample: 'Hola (xin chào)' },
          { char: 'I i', reading: 'i', meaningOrExample: 'Isla (hòn đảo)' },
          { char: 'J j', reading: 'jota [x] (kh)', meaningOrExample: 'Jardín (khu vườn)' },
          { char: 'K k', reading: 'ka', meaningOrExample: 'Kilómetro' },
          { char: 'L l', reading: 'ele', meaningOrExample: 'Luna (mặt trăng)' },
          { char: 'M m', reading: 'eme', meaningOrExample: 'Mundo (thế giới)' },
          { char: 'N n', reading: 'ene', meaningOrExample: 'Noche (đêm)' },
          { char: 'Ñ ñ', reading: 'eñe [ɲ] (nh)', meaningOrExample: 'España (Tây Ban Nha), Mañana' },
          { char: 'O o', reading: 'o', meaningOrExample: 'Océano (đại dương)' },
          { char: 'P p', reading: 'pe', meaningOrExample: 'Paz (hòa bình)' },
          { char: 'Q q', reading: 'cu', meaningOrExample: 'Queso (pho mát)' },
          { char: 'R r', reading: 'ere [r]', meaningOrExample: 'Río (dòng sông)' },
          { char: 'S s', reading: 'ese', meaningOrExample: 'Sol (mặt trời)' },
          { char: 'T t', reading: 'te', meaningOrExample: 'Tiempo (thời gian)' },
          { char: 'U u', reading: 'u', meaningOrExample: 'Uva (quả nho)' },
          { char: 'V v', reading: 'uve', meaningOrExample: 'Vida (cuộc sống)' },
          { char: 'W w', reading: 'uve doble', meaningOrExample: 'Web' },
          { char: 'X x', reading: 'equis', meaningOrExample: 'Éxito (thành công)' },
          { char: 'Y y', reading: 'ye / i griega', meaningOrExample: 'Yate' },
          { char: 'Z z', reading: 'zeta [θ] hoặc [s]', meaningOrExample: 'Zumo (nước ép)' },
        ],
      },
      {
        title: 'Chữ Đôi & Nguyên Âm Dấu Trọng Âm',
        description: 'Quy tắc rung lưỡi kép Rr, chữ Ll và dấu trọng âm (Acento ortográfico).',
        characters: [
          { char: 'RR rr', reading: 'erre doble (rung lưỡi mạnh)', meaningOrExample: 'Perro (con chó), Carro' },
          { char: 'LL ll', reading: 'elle [ʝ] (y/gi)', meaningOrExample: 'Lluvia (cơn mưa), Calle' },
          { char: 'CH ch', reading: 'che [tʃ]', meaningOrExample: 'Chico (cậu bé), Noche' },
          { char: 'Á, É, Í, Ó, Ú', reading: 'Nguyên âm nhấn trọng âm', meaningOrExample: 'Música, Corazón, Café' },
          { char: 'Ü ü', reading: 'u phát âm khi đứng giữa g và e/i', meaningOrExample: 'Pingüino (chim cánh cụt)' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  8. PHÁP (fr)
  // ──────────────────────────────────────────────────────────
  fr: {
    lang: 'fr',
    title: 'Alphabet Français (Tiếng Pháp)',
    systemType: 'Bảng chữ cái Latinh 26 chữ cái kèm 5 hệ dấu phụ thanh âm',
    description: 'Bao gồm 26 chữ cái, các dấu phụ (aigu, grave, circonflexe, cédille, tréma), âm mũi và liên kết nối âm.',
    sections: [
      {
        title: 'Bảng 26 Chữ Cái Tiếng Pháp A-Z',
        description: 'Tên gọi chữ cái theo ngữ âm Pháp.',
        characters: [
          { char: 'A a', reading: '[a]', meaningOrExample: 'Amour (tình yêu)' },
          { char: 'B b', reading: '[be]', meaningOrExample: 'Beau (xinh đẹp)' },
          { char: 'C c', reading: '[se]', meaningOrExample: 'Ciel (bầu trời)' },
          { char: 'D d', reading: '[de]', meaningOrExample: 'Douceur (ngọt ngào)' },
          { char: 'E e', reading: '[ə]', meaningOrExample: 'Enfant (đứa trẻ)' },
          { char: 'F f', reading: '[ɛf]', meaningOrExample: 'Fleur (bông hoa)' },
          { char: 'G g', reading: '[ʒe]', meaningOrExample: 'Gare (nhà ga)' },
          { char: 'H h', reading: '[aʃ] (câm)', meaningOrExample: 'Homme (người đàn ông)' },
          { char: 'I i', reading: '[i]', meaningOrExample: 'Idée (ý tưởng)' },
          { char: 'J j', reading: '[ʒi]', meaningOrExample: 'Jour (ngày)' },
          { char: 'K k', reading: '[ka]', meaningOrExample: 'Kiosque' },
          { char: 'L l', reading: '[ɛl]', meaningOrExample: 'Lumière (ánh sáng)' },
          { char: 'M m', reading: '[ɛm]', meaningOrExample: 'Monde (thế giới)' },
          { char: 'N n', reading: '[ɛn]', meaningOrExample: 'Nuit (đêm)' },
          { char: 'O o', reading: '[o]', meaningOrExample: 'Oiseau (chú chim)' },
          { char: 'P p', reading: '[pe]', meaningOrExample: 'Paix (hòa bình)' },
          { char: 'Q q', reading: '[ky]', meaningOrExample: 'Quatre (số 4)' },
          { char: 'R r', reading: '[ɛʁ] (rung họng)', meaningOrExample: 'Rêve (giấc mơ)' },
          { char: 'S s', reading: '[ɛs]', meaningOrExample: 'Soleil (mặt trời)' },
          { char: 'T t', reading: '[te]', meaningOrExample: 'Temps (thời gian)' },
          { char: 'U u', reading: '[y] (u chu môi)', meaningOrExample: 'Unique (duy nhất)' },
          { char: 'V v', reading: '[ve]', meaningOrExample: 'Vie (cuộc sống)' },
          { char: 'W w', reading: '[dubləve]', meaningOrExample: 'Week-end' },
          { char: 'X x', reading: '[iks]', meaningOrExample: 'Extra' },
          { char: 'Y y', reading: '[igʁɛk]', meaningOrExample: 'Yeux (đôi mắt)' },
          { char: 'Z z', reading: '[zɛd]', meaningOrExample: 'Zéro (số 0)' },
        ],
      },
      {
        title: '5 Loại Dấu Phụ & Ký Tự Ghép Đặc Trưng',
        description: 'Dấu phụ giúp thay đổi độ mở của miệng và cao độ âm sắc.',
        characters: [
          { char: 'é', name: 'Accent aigu (dấu sắc)', reading: 'e đóng [e]', meaningOrExample: 'Été (mùa hè), Café' },
          { char: 'è, à, ù', name: 'Accent grave (dấu huyền)', reading: 'e mở [ɛ]', meaningOrExample: 'Mère (mẹ), Où (ở đâu)' },
          { char: 'â, ê, î, ô, û', name: 'Accent circonflexe (dấu mũ)', reading: 'kéo dài nguyên âm', meaningOrExample: 'Fête (lễ hội), Forêt (rừng)' },
          { char: 'ç', name: 'Cédille (dấu móc dưới)', reading: 'đọc là [s] trước a, o, u', meaningOrExample: 'Français (tiếng Pháp), Garçon' },
          { char: 'ë, ï, ü', name: 'Tréma (dấu hai chấm)', reading: 'tách riêng nguyên âm', meaningOrExample: 'Noël (Giáng sinh), Maïs' },
          { char: 'œ, æ', name: 'Ligatures (chữ dính)', reading: 'nguyên âm đôi', meaningOrExample: 'Cœur (trái tim), Œil (mắt)' },
        ],
      },
      {
        title: 'Các Âm Mũi Thanh Lịch (Voyelles Nasales)',
        description: 'Luồng khí đi qua cả khoang miệng và khoang mũi.',
        characters: [
          { char: 'an, am, en, em', reading: '[ɑ̃] (ăng)', meaningOrExample: 'Enfant, Temps (thời gian)' },
          { char: 'in, im, ain, ein', reading: '[ɛ̃] (anh)', meaningOrExample: 'Vin (rượu vang), Pain (bánh mì)' },
          { char: 'on, om', reading: '[ɔ̃] (ông)', meaningOrExample: 'Bon (tốt), Maison (ngôi nhà)' },
          { char: 'un, um', reading: '[œ̃] (ưng)', meaningOrExample: 'Un (số một), Parfum (nước hoa)' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  9. Ý (it)
  // ──────────────────────────────────────────────────────────
  it: {
    lang: 'it',
    title: 'Alfabeto Italiano (Tiếng Ý)',
    systemType: 'Bảng chữ cái Latinh 21 chữ cái truyền thống',
    description: 'Chỉ gồm 21 chữ cái truyền thống (J, K, W, X, Y là chữ mượn), rất giàu nhạc tính nhờ kết thúc bằng nguyên âm.',
    sections: [
      {
        title: '21 Chữ Cái Truyền Thống A-Z',
        description: 'Cách đọc chuẩn âm Ý.',
        characters: [
          { char: 'A a', reading: 'a', meaningOrExample: 'Amore (tình yêu)' },
          { char: 'B b', reading: 'bi', meaningOrExample: 'Bello (xinh đẹp)' },
          { char: 'C c', reading: 'ci [k/tʃ]', meaningOrExample: 'Ciao (xin chào), Cuore' },
          { char: 'D d', reading: 'di', meaningOrExample: 'Dolce (ngọt ngào)' },
          { char: 'E e', reading: 'e', meaningOrExample: 'Estate (mùa hè)' },
          { char: 'F f', reading: 'effe', meaningOrExample: 'Fiore (bông hoa)' },
          { char: 'G g', reading: 'gi [ɡ/dʒ]', meaningOrExample: 'Giorno (ngày), Gatto' },
          { char: 'H h', reading: 'acca (luôn câm)', meaningOrExample: 'Hanno (họ có)' },
          { char: 'I i', reading: 'i', meaningOrExample: 'Italia' },
          { char: 'L l', reading: 'elle', meaningOrExample: 'Luce (ánh sáng)' },
          { char: 'M m', reading: 'emme', meaningOrExample: 'Mare (biển)' },
          { char: 'N n', reading: 'enne', meaningOrExample: 'Notte (đêm)' },
          { char: 'O o', reading: 'o', meaningOrExample: 'Oro (vàng)' },
          { char: 'P p', reading: 'pi', meaningOrExample: 'Pace (hòa bình)' },
          { char: 'Q q', reading: 'qu', meaningOrExample: 'Quadro (bức tranh)' },
          { char: 'R r', reading: 'erre (rung đầu lưỡi)', meaningOrExample: 'Roma, Rosa (hoa hồng)' },
          { char: 'S s', reading: 'esse', meaningOrExample: 'Sole (mặt trời)' },
          { char: 'T t', reading: 'ti', meaningOrExample: 'Tempo (thời gian)' },
          { char: 'U u', reading: 'u', meaningOrExample: 'Universo (vũ trụ)' },
          { char: 'V v', reading: 'vi', meaningOrExample: 'Vita (cuộc sống)' },
          { char: 'Z z', reading: 'zeta [ts/dz]', meaningOrExample: 'Zero, Pizza' },
        ],
      },
      {
        title: '5 Chữ Cái Ngoại Lai & Quy Tắc Phát Âm',
        description: 'Chữ mượn (Lettere straniere) và quy tắc phát âm C/G, GLI, GN.',
        characters: [
          { char: 'J, K, W, X, Y', reading: 'Chữ cái mượn', meaningOrExample: 'Jeans, Kiwi, Web, Taxi, Yoga' },
          { char: 'GLI', reading: '[ʎ] (l-y mềm)', meaningOrExample: 'Famiglia (gia đình), Figlio' },
          { char: 'GN', reading: '[ɲ] (nh)', meaningOrExample: 'Gnocchi, Montagna (ngọn núi)' },
          { char: 'SC (sce, sci)', reading: '[ʃ] (s nặng)', meaningOrExample: 'Scuola, Scelta (lựa chọn)' },
          { char: 'CH & GH', reading: '[k] & [ɡ] trước e, i', meaningOrExample: 'Spaghetti, Chiesa (nhà thờ)' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  10. ĐỨC (de)
  // ──────────────────────────────────────────────────────────
  de: {
    lang: 'de',
    title: 'Deutsches Alphabet (Tiếng Đức)',
    systemType: 'Bảng chữ cái Latinh với 3 Umlaute & Eszett (ß)',
    description: '26 chữ cái Latinh tiêu chuẩn cộng thêm 3 biến âm Umlaute (Ä, Ö, Ü) và ký tự Eszett (ß).',
    sections: [
      {
        title: '26 Chữ Cái Tiếng Đức A-Z',
        description: 'Tên gọi theo ngữ âm Đức chuẩn (Hochdeutsch).',
        characters: [
          { char: 'A a', reading: '[aː]', meaningOrExample: 'Abend (buổi tối)' },
          { char: 'B b', reading: '[beː]', meaningOrExample: 'Buch (cuốn sách)' },
          { char: 'C c', reading: '[tseː]', meaningOrExample: 'Café, Computer' },
          { char: 'D d', reading: '[deː]', meaningOrExample: 'Danke (cảm ơn)' },
          { char: 'E e', reading: '[eː]', meaningOrExample: 'Erde (trái đất)' },
          { char: 'F f', reading: '[ɛf]', meaningOrExample: 'Freiheit (tự do)' },
          { char: 'G g', reading: '[ɡeː]', meaningOrExample: 'Garten (khu vườn)' },
          { char: 'H h', reading: '[haː]', meaningOrExample: 'Haus (ngôi nhà)' },
          { char: 'I i', reading: '[iː]', meaningOrExample: 'Insel (hòn đảo)' },
          { char: 'J j', reading: '[jɔt]', meaningOrExample: 'Jahr (năm)' },
          { char: 'K k', reading: '[kaː]', meaningOrExample: 'Kind (đứa trẻ)' },
          { char: 'L l', reading: '[ɛl]', meaningOrExample: 'Liebe (tình yêu)' },
          { char: 'M m', reading: '[ɛm]', meaningOrExample: 'Mond (mặt trăng)' },
          { char: 'N n', reading: '[ɛn]', meaningOrExample: 'Nacht (đêm)' },
          { char: 'O o', reading: '[oː]', meaningOrExample: 'Ozean (đại dương)' },
          { char: 'P p', reading: '[peː]', meaningOrExample: 'Platz (quảng trường)' },
          { char: 'Q q', reading: '[kuː]', meaningOrExample: 'Quelle (nguồn nước)' },
          { char: 'R r', reading: '[ɛʁ]', meaningOrExample: 'Regen (cơn mưa)' },
          { char: 'S s', reading: '[ɛs]', meaningOrExample: 'Sonne (mặt trời)' },
          { char: 'T t', reading: '[teː]', meaningOrExample: 'Traum (giấc mơ)' },
          { char: 'U u', reading: '[uː]', meaningOrExample: 'Uhr (đồng hồ)' },
          { char: 'V v', reading: '[faʊ] (đọc như f)', meaningOrExample: 'Vater (người cha), Vogel' },
          { char: 'W w', reading: '[veː] (đọc như v)', meaningOrExample: 'Wasser (nước), Welt' },
          { char: 'X x', reading: '[ɪks]', meaningOrExample: 'Xylophon' },
          { char: 'Y y', reading: '[ˈʏpsilɔn]', meaningOrExample: 'Yoga' },
          { char: 'Z z', reading: '[tsɛt] (đọc như ts)', meaningOrExample: 'Zeit (thời gian), Zug' },
        ],
      },
      {
        title: '3 Umlaute & Ký Tự Đặc Biệt Eszett (ß)',
        description: 'Biến âm nguyên âm và phụ âm kép đặc trưng.',
        characters: [
          { char: 'Ä ä', name: 'A-Umlaut', reading: '[ɛː] / [ɛ] (e mở)', meaningOrExample: 'Mädchen (cô bé), Äpfel (những quả táo)' },
          { char: 'Ö ö', name: 'O-Umlaut', reading: '[øː] / [œ]', meaningOrExample: 'Schön (đẹp đẽ), Öffnen (mở cửa)' },
          { char: 'Ü ü', name: 'U-Umlaut', reading: '[yː] / [ʏ] (u chu môi)', meaningOrExample: 'Glück (hạnh phúc), Über (ở trên)' },
          { char: 'ß', name: 'Eszett / Scharfes S', reading: '[s] (s sắc kép)', meaningOrExample: 'Straße (con đường), Groß (to lớn)' },
        ],
      },
      {
        title: 'Các Tổ Hợp Âm Tiếng Đức Quan Trọng',
        description: 'Quy tắc ghép vần tạo nên âm hưởng trang trọng của tiếng Đức.',
        characters: [
          { char: 'EI', reading: '[aɪ] (ai)', meaningOrExample: 'Eins (số một), Freiheit (tự do)' },
          { char: 'IE', reading: '[iː] (i dài)', meaningOrExample: 'Liebe (tình yêu), Lied (bài hát)' },
          { char: 'EU / ÄU', reading: '[ɔʏ] (oi)', meaningOrExample: 'Freund (bạn bè), Häuser (những ngôi nhà)' },
          { char: 'CH', reading: '[ç] (sau e, i) / [x] (sau a, o, u)', meaningOrExample: 'Ich (tôi), Bach (dòng suối)' },
          { char: 'SCH', reading: '[ʃ] (s nặng)', meaningOrExample: 'Schule (trường), Schnee (tuyết)' },
          { char: 'TSCH', reading: '[tʃ] (ch)', meaningOrExample: 'Tschüss (tạm biệt), Deutschland' },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  //  11. BỒ ĐÀO NHA (pt)
  // ──────────────────────────────────────────────────────────
  pt: {
    lang: 'pt',
    title: 'Alfabeto Português (Tiếng Bồ Đào Nha)',
    systemType: 'Bảng chữ cái Latinh với dấu ngã Til và dấu mũ',
    description: '26 chữ cái cơ bản cộng thêm các dấu ngã Til (ã, õ) biểu thị âm mũi, Cedilha (ç) và dấu trọng âm.',
    sections: [
      {
        title: '26 Chữ Cái Tiếng Bồ Đào Nha A-Z',
        description: 'Tên gọi chữ cái theo ngữ âm chuẩn.',
        characters: [
          { char: 'A a', reading: 'á', meaningOrExample: 'Amor (tình yêu)' },
          { char: 'B b', reading: 'bê', meaningOrExample: 'Bom (tốt lành)' },
          { char: 'C c', reading: 'cê', meaningOrExample: 'Céu (bầu trời)' },
          { char: 'D d', reading: 'dê', meaningOrExample: 'Dia (ngày)' },
          { char: 'E e', reading: 'é', meaningOrExample: 'Estrela (ngôi sao)' },
          { char: 'F f', reading: 'efe', meaningOrExample: 'Fogo (lửa)' },
          { char: 'G g', reading: 'gê / guê', meaningOrExample: 'Gato (mèo)' },
          { char: 'H h', reading: 'agá (luôn câm)', meaningOrExample: 'Hoje (hôm nay)' },
          { char: 'I i', reading: 'i', meaningOrExample: 'Ilha (hòn đảo)' },
          { char: 'J j', reading: 'jota [ʒ]', meaningOrExample: 'Janela (cửa sổ)' },
          { char: 'K k', reading: 'cá', meaningOrExample: 'Km' },
          { char: 'L l', reading: 'ele', meaningOrExample: 'Lua (mặt trăng)' },
          { char: 'M m', reading: 'eme', meaningOrExample: 'Mundo (thế giới)' },
          { char: 'N n', reading: 'ene', meaningOrExample: 'Noite (đêm)' },
          { char: 'O o', reading: 'ó', meaningOrExample: 'Oceano (đại dương)' },
          { char: 'P p', reading: 'pê', meaningOrExample: 'Paz (hòa bình)' },
          { char: 'Q q', reading: 'quê', meaningOrExample: 'Queijo (pho mát)' },
          { char: 'R r', reading: 'erre', meaningOrExample: 'Rio (sông)' },
          { char: 'S s', reading: 'esse', meaningOrExample: 'Sol (mặt trời)' },
          { char: 'T t', reading: 'tê', meaningOrExample: 'Tempo (thời gian)' },
          { char: 'U u', reading: 'u', meaningOrExample: 'Universo (vũ trụ)' },
          { char: 'V v', reading: 'vê', meaningOrExample: 'Vida (cuộc sống)' },
          { char: 'W w', reading: 'dáblio', meaningOrExample: 'Web' },
          { char: 'X x', reading: 'xis', meaningOrExample: 'Xícara (tách)' },
          { char: 'Y y', reading: 'ípsilon', meaningOrExample: 'Yoga' },
          { char: 'Z z', reading: 'zê', meaningOrExample: 'Zero' },
        ],
      },
      {
        title: 'Dấu Ngã Til & Các Dấu Phụ Âm Mũi',
        description: 'Đặc trưng âm học nổi bật nhất của tiếng Bồ Đào Nha.',
        characters: [
          { char: 'Ã ã', name: 'A com til', reading: '[ɐ̃] (a mũi)', meaningOrExample: 'Amanhã (ngày mai), Pão (bánh mì)' },
          { char: 'Õ õ', name: 'O com til', reading: '[õ] (ô mũi)', meaningOrExample: 'Corações (những trái tim)' },
          { char: 'Ç ç', name: 'C cedilha', reading: '[s] trước a, o, u', meaningOrExample: 'Coração (trái tim), Praça (quảng trường)' },
          { char: 'Á, É, Í, Ó, Ú', name: 'Acento agudo', reading: 'nguyên âm mở, nhấn mạnh', meaningOrExample: 'Água (nước), Café (cà phê)' },
          { char: 'Â, Ê, Ô', name: 'Acento circunflexo', reading: 'nguyên âm đóng', meaningOrExample: 'Você (bạn), Avô (ông)' },
          { char: 'ÃO / ÕES', name: 'Nguyên âm đôi mũi', reading: '[ɐ̃w̃] / [õj̃s]', meaningOrExample: 'Não (không), Lições (bài học)' },
        ],
      },
    ],
  },
};
